/* Shared display names for the library and random scroll rack. */
const CORPUS_LABELS = {
  "locations": {
    "The Sun Station": "太阳站",
    "Escape Pod 2": "2号逃生舱",
    "Escape Pod 3": "3号逃生舱",
    "Escape pod 1": "1号逃生舱",
    "The Sunless City": "背阴城",
    "Stepping Stone District": "垫脚石区",
    "Eye Shrine District": "眼祭坛区",
    "School district": "学校区",
    "High Energy Lab": "高能实验室",
    "Quantum Moon Locator": "量子卫星定位器",
    "Lakebed Cave": "湖底洞穴",
    "Ash Twin Core": "灰烬双星核心",
    "The Vessel": "飞船",
    "Black Hole Forge": "黑洞熔炉",
    "Southern Observatory": "南部天文台",
    "Gravity Cannon": "重力炮",
    "Tower of Quantum Knowledge": "量子知识之塔",
    "Orbital Probe Cannon": "轨道探测炮",
    "Construction Yard Island": "建造厂",
    "Statue island": "雕像岛",
    "Sixth Location": "第六个位置",
    "White Hole Station": "白洞站",
    "Nomai Shuttle": "挪麦航天飞机",
    "Gravity Bridge": "重力桥",
    "Mining Site 2b": "采矿点2b",
    "Hollow’s lantern": "空心灯",
    "North pole": "北极",
    "Control Module": "控制模块",
    "Launch Module": "发射模块",
    "Probe Tracking Module": "探测器跟踪模块",
    "Quantum Trials": "量子试炼",
    "Anglerfish Overlook District": "安康鱼瞭望台区",
    "Quantum Cave": "量子洞穴",
    "Southern Quantum Caves": "南方量子洞穴",
    "Sun Station Warp Tower": "太阳站跃迁塔",
    "Hourglass Twins Warp Tower": "沙漏双星跃迁塔",
    "Brittle Hollow Warp Tower": "碎空星跃迁塔",
    "Meltwater District": "融水区",
    "Eye shrine": "眼祭坛",
    "Vessel Crash Room": "太空船坠毁室",
    "Insignificant Buildings": "无关紧要的建筑",
    "Underwater ruins": "水下遗迹",
    "Eye Signal Locator": "宇宙之眼信号定位器",
    "Inside": "内部"
  },
  "speakers": {
    "SECCA": "塞卡",
    "ANNONA": "安诺纳",
    "AVENS": "埃文斯",
    "BELLS": "贝尔斯",
    "BROMI": "布洛密",
    "BUR": "伯尔",
    "CANNA": "卡纳",
    "CASSAVA": "卡萨瓦",
    "CLARY": "克莱瑞",
    "CLEM": "克莱姆",
    "COLEUS": "科利耶斯",
    "CONOY": "科诺伊",
    "CYCAD": "赛卡德",
    "DAZ": "戴兹",
    "DIN": "迪恩",
    "ESCALL": "艾斯科尔",
    "FILIX": "费利克斯",
    "HYSSOP": "希索普",
    "IDAEA": "伊代亚",
    "ILEX": "艾莱克斯",
    "KOUSA": "库萨",
    "LAEVI": "莱阿维",
    "LAMI": "拉米",
    "MALLOW": "玛罗",
    "MELORAE": "梅洛瑞",
    "MITIS": "米提斯",
    "NEEM": "尼姆",
    "OENO": "奥埃诺",
    "PHLOX": "弗拉克斯",
    "PLUME": "普鲁姆",
    "POKE": "珀克",
    "PRIVET": "普利维特",
    "PYE": "派伊",
    "RAMIE": "瑞米",
    "RHUS": "鲁斯",
    "ROOT": "鲁特",
    "SOLANUM": "所莱内姆",
    "SPIRE": "斯拜尔",
    "TAGET": "塔格特",
    "THATCH": "萨奇",
    "YARROW": "亚罗"
  }
};
